format-version=1
profile-id=atm10-normal-8.0_silentgear-4.2.1.1_neoforge-21.1.247
minecraft-version=1.21.1
minecraft-protocol=767
curseforge-client-file-id=8649077
curseforge-server-file-id=8649107
client-full-contract-sha256=a61293a54b0f80c83b73b5e2968e8de08b9595771110fa7c7cbea9e55ad2892f
frozen-registry-sequence-sha256=8fda0099a55ad36898adbf43dc77d5b702c6d4c5c26c1bcddb3039669dd00269
vanilla-block-report.bytes=5585490
vanilla-block-report.sha256=0dde7f869588905763ea6ff2e7e01bec1db740a58d27477fd27c2f07fb029f73
vanilla-state-table.count=26684
vanilla-state-table.bytes=2353080
vanilla-state-table.sha256=de9980fae71fecd0112d77cd1c056815dca3a1e1125289efd08b1c0696f499bb
client-global-state.count=1980659
client-minecraft-state-table.count=45481
client-minecraft-state-table.bytes=4931283
client-minecraft-state-table.sha256=ae1d2612f838f8b22f6bc2bd86f46d0cbab26566401f36b6496c53cb2592dc12
reviewed-map-tsv.count=26684
reviewed-map-tsv.bytes=2505236
reviewed-map-tsv.sha256=97a1dd540d706a09c4d59cae8fed0319534db2a385f9d09dc319072a9ca9f07f
map.file=block-state-map.bin
map.bytes=69272
map.sha256=6015f4b9f30e0d680d8d89439fad7f141eb901462a04bf4052865b0fec6fe263
map.count=26684
map.maximum-target-id=45478
source-global-palette.bits=15
target-global-palette.bits=21
neutral-extra-property.count=3
neutral-extra-property.0.name=essentia_logged
neutral-extra-property.0.block-count=337
neutral-extra-property.0.value=false
neutral-extra-property.1.name=boiling
neutral-extra-property.1.block-count=1
neutral-extra-property.1.value=false
neutral-extra-property.2.name=waterlogged
neutral-extra-property.2.block-count=14
neutral-extra-property.2.value=false
protocol-report.bytes=16264
protocol-report.sha256=6f613707a721fa9dec64f79f35527ec6884ee762fd5620930f9d72543178c3ca
packet.add-entity=1
packet.block-update=9
packet.level-chunk-with-light=39
packet.level-event=40
packet.level-particles=41
packet.section-blocks-update=73
packet.set-entity-data=88
particle.block=1
particle.block-marker=2
particle.falling-dust=28
particle.dust-pillar=105
entity.falling-block=40
