format-version=3
pack=ATM10-8.0
minecraft=1.21.1
neoforge=21.1.247
selection=encoded-entries-minus-exact-vanilla-known-pack-entry-ids
known-pack.count=1
known-pack.0=minecraft:core:1.21.1
known-pack-entry.count=313
known-pack-entry.sequence-sha256=56f0ce758b71b436b6c7c69ac671122cc252efa49c5af9ebc2efaf59ed87fa85
omitted-known-pack-entry.count=18
omitted-known-pack-entry.sequence-sha256=b9dd6e9c6e783f8a2773dda779e0aea965204e2334e490041c794f5f59a3cab8
omitted-known-pack-entry.0.registry=minecraft:dimension_type
omitted-known-pack-entry.0.entry=minecraft:the_end
omitted-known-pack-entry.1.registry=minecraft:enchantment
omitted-known-pack-entry.1.entry=minecraft:channeling
omitted-known-pack-entry.2.registry=minecraft:enchantment
omitted-known-pack-entry.2.entry=minecraft:protection
omitted-known-pack-entry.3.registry=minecraft:enchantment
omitted-known-pack-entry.3.entry=minecraft:sharpness
omitted-known-pack-entry.4.registry=minecraft:wolf_variant
omitted-known-pack-entry.4.entry=minecraft:ashen
omitted-known-pack-entry.5.registry=minecraft:wolf_variant
omitted-known-pack-entry.5.entry=minecraft:black
omitted-known-pack-entry.6.registry=minecraft:wolf_variant
omitted-known-pack-entry.6.entry=minecraft:chestnut
omitted-known-pack-entry.7.registry=minecraft:wolf_variant
omitted-known-pack-entry.7.entry=minecraft:pale
omitted-known-pack-entry.8.registry=minecraft:wolf_variant
omitted-known-pack-entry.8.entry=minecraft:rusty
omitted-known-pack-entry.9.registry=minecraft:wolf_variant
omitted-known-pack-entry.9.entry=minecraft:snowy
omitted-known-pack-entry.10.registry=minecraft:wolf_variant
omitted-known-pack-entry.10.entry=minecraft:spotted
omitted-known-pack-entry.11.registry=minecraft:wolf_variant
omitted-known-pack-entry.11.entry=minecraft:striped
omitted-known-pack-entry.12.registry=minecraft:wolf_variant
omitted-known-pack-entry.12.entry=minecraft:woods
omitted-known-pack-entry.13.registry=minecraft:worldgen/biome
omitted-known-pack-entry.13.entry=minecraft:end_barrens
omitted-known-pack-entry.14.registry=minecraft:worldgen/biome
omitted-known-pack-entry.14.entry=minecraft:end_highlands
omitted-known-pack-entry.15.registry=minecraft:worldgen/biome
omitted-known-pack-entry.15.entry=minecraft:end_midlands
omitted-known-pack-entry.16.registry=minecraft:worldgen/biome
omitted-known-pack-entry.16.entry=minecraft:small_end_islands
omitted-known-pack-entry.17.registry=minecraft:worldgen/biome
omitted-known-pack-entry.17.entry=minecraft:the_end
registry.count=50
registry.total-entries=1946
registry.total-encoded-data-entries=1946
registry.total-bytes=651622
registry.sequence-sha256=e78c792986feed4fe861994cceb7ffb6dc24401feda7a600f272c6eef74a0935
registry.0.name=aether:moa_type
registry.0.file=dynamic-registries/aether_moa_type.bin
registry.0.entries=3
registry.0.encoded-data-entries=3
registry.0.bytes=689
registry.0.sha256=4394bb4ae1c1a608dfeddd51273140d693cbc9fbb55f5eb6763c6a76bfb7a6cc
registry.1.name=compactmachines:room_templates
registry.1.file=dynamic-registries/compactmachines_room_templates.bin
registry.1.entries=8
registry.1.encoded-data-entries=8
registry.1.bytes=850
registry.1.sha256=f3e1ce411b19452259a050e2eaef945b2d84b9758b4463d6278e1f767df6c445
registry.2.name=computercraft:pocket_upgrade
registry.2.file=dynamic-registries/computercraft_pocket_upgrade.bin
registry.2.entries=8
registry.2.encoded-data-entries=8
registry.2.bytes=1012
registry.2.sha256=f49b9ce4094621a76bf074eb72aba5d892aebb4a3e2b2c6e61ab95546afa82fe
registry.3.name=computercraft:turtle_overlay
registry.3.file=dynamic-registries/computercraft_turtle_overlay.bin
registry.3.entries=2
registry.3.encoded-data-entries=2
registry.3.bytes=230
registry.3.sha256=bf61a08a2afd5a3f8e0b943f3d0f8423367089d6124c119ba81dba5dc0602c78
registry.4.name=computercraft:turtle_upgrade
registry.4.file=dynamic-registries/computercraft_turtle_upgrade.bin
registry.4.entries=21
registry.4.encoded-data-entries=21
registry.4.bytes=3067
registry.4.sha256=7ea1c3cadb67c9efef8cce1a89eaad4702434022209f8d43d680a36650874949
registry.5.name=create:potato_projectile/type
registry.5.file=dynamic-registries/create_potato_projectile_type.bin
registry.5.entries=34
registry.5.encoded-data-entries=34
registry.5.bytes=8510
registry.5.sha256=18b6e5789cac8b4fa229af5bbfe8444350fdce44ebcfc445c62c3a7a5818b442
registry.6.name=create_aquatic_ambitions:conduit_effect
registry.6.file=dynamic-registries/create_aquatic_ambitions_conduit_effect.bin
registry.6.entries=24
registry.6.encoded-data-entries=24
registry.6.bytes=4797
registry.6.sha256=80baae0d4b44e53f2291a38c0c0288886a68635ca3d80696dc277bc8bc3dd3d7
registry.7.name=enderio:conduit
registry.7.file=dynamic-registries/enderio_conduit.bin
registry.7.entries=17
registry.7.encoded-data-entries=17
registry.7.bytes=2756
registry.7.sha256=885d5492d597186dfd519c5f47273a3a43e029807f8cb332ec1bc082772efb8a
registry.8.name=eternal_starlight:astral_golem_material
registry.8.file=dynamic-registries/eternal_starlight_astral_golem_material.bin
registry.8.entries=2
registry.8.encoded-data-entries=2
registry.8.bytes=469
registry.8.sha256=a9590f102983320f39502601bac76fbad3bf771b679ccac3a70c000d3c33762f
registry.9.name=eternal_starlight:biome_data
registry.9.file=dynamic-registries/eternal_starlight_biome_data.bin
registry.9.entries=23
registry.9.encoded-data-entries=23
registry.9.bytes=3695
registry.9.sha256=e24bcd4556bd3420438088db6107fda4d626999ad6c3f2fbf0e5264379333b7e
registry.10.name=eternal_starlight:boarwarf_type
registry.10.file=dynamic-registries/eternal_starlight_boarwarf_type.bin
registry.10.entries=3
registry.10.encoded-data-entries=3
registry.10.bytes=426
registry.10.sha256=084f71205f917cf8ce85ea723f2086c41543a3ceee171abd1eae0143db74250f
registry.11.name=eternal_starlight:crest
registry.11.file=dynamic-registries/eternal_starlight_crest.bin
registry.11.entries=11
registry.11.encoded-data-entries=11
registry.11.bytes=2131
registry.11.sha256=0a8a956c3ae9e8183a767fd02e9f1655a2f5ab7ccf1c2950d33b7abf098c3ec2
registry.12.name=eternal_starlight:ent_variant
registry.12.file=dynamic-registries/eternal_starlight_ent_variant.bin
registry.12.entries=4
registry.12.encoded-data-entries=4
registry.12.bytes=779
registry.12.sha256=bd8e727e5b7e8bb6d0edbf739a1be22ad1c4362623d836506d9d94fd174df767
registry.13.name=eternal_starlight:seeds_launcher_ammo_type
registry.13.file=dynamic-registries/eternal_starlight_seeds_launcher_ammo_type.bin
registry.13.entries=8
registry.13.encoded-data-entries=8
registry.13.bytes=1084
registry.13.sha256=8d28a859d6844620f7b34327949db5d4e2fed2e7ac0b2038c0b33e4a287c6358
registry.14.name=eternal_starlight:seeker_variant
registry.14.file=dynamic-registries/eternal_starlight_seeker_variant.bin
registry.14.entries=2
registry.14.encoded-data-entries=2
registry.14.bytes=775
registry.14.sha256=a624c5181fcc8f80e2acfb2b3a1c2723b728fbb323f9dc0abdac21bf7bbea3bf
registry.15.name=eternal_starlight:shimmer_lacewing_variant
registry.15.file=dynamic-registries/eternal_starlight_shimmer_lacewing_variant.bin
registry.15.entries=2
registry.15.encoded-data-entries=2
registry.15.bytes=435
registry.15.sha256=f2561492f8e03397554be8cd5b69bc8c0ae3c05e68ccd8fc4da3c9e2adbcb546
registry.16.name=forbidden_arcanus:enhancer/definition
registry.16.file=dynamic-registries/forbidden_arcanus_enhancer_definition.bin
registry.16.entries=7
registry.16.encoded-data-entries=7
registry.16.bytes=1565
registry.16.sha256=3c4558557616ee8f202e37b99d85430a42ad108f4bc229b41b2c0cd8af8e3003
registry.17.name=forbidden_arcanus:hephaestus_forge/ritual
registry.17.file=dynamic-registries/forbidden_arcanus_hephaestus_forge_ritual.bin
registry.17.entries=43
registry.17.encoded-data-entries=43
registry.17.bytes=29431
registry.17.sha256=eac60872661fda0816dc30fb576f955074fe7c5625aa31b690ff0270ba7e55d8
registry.18.name=forbidden_arcanus:item_modifier
registry.18.file=dynamic-registries/forbidden_arcanus_item_modifier.bin
registry.18.entries=6
registry.18.encoded-data-entries=6
registry.18.bytes=2747
registry.18.sha256=f9e8f17168ab512898c1de25700876003527057682492cb2648db0f6e6c3891f
registry.19.name=forbidden_arcanus:magic_circle
registry.19.file=dynamic-registries/forbidden_arcanus_magic_circle.bin
registry.19.entries=3
registry.19.encoded-data-entries=3
registry.19.bytes=620
registry.19.sha256=16c558d5447b89fcc8c75ea59cacc6527cf61511f471aadc2619a66a932fbd4e
registry.20.name=forbidden_arcanus:research/constellation
registry.20.file=dynamic-registries/forbidden_arcanus_research_constellation.bin
registry.20.entries=1
registry.20.encoded-data-entries=1
registry.20.bytes=166
registry.20.sha256=38cf3a85a054456fa3af52e4a0b1e06a9e24c43e0d655a71d0673fe507c20474
registry.21.name=forbidden_arcanus:research/knowledge
registry.21.file=dynamic-registries/forbidden_arcanus_research_knowledge.bin
registry.21.entries=3
registry.21.encoded-data-entries=3
registry.21.bytes=810
registry.21.sha256=2e0a78648b776dfa573db053b53841f6612528c16d33debc12297abd64cdb599
registry.22.name=forbidden_arcanus:residue_type
registry.22.file=dynamic-registries/forbidden_arcanus_residue_type.bin
registry.22.entries=11
registry.22.encoded-data-entries=11
registry.22.bytes=1964
registry.22.sha256=c1f5fcda2288160ddebd0b6f44ea76b4c5cc5872127e57550c2b56b1cdb8f22e
registry.23.name=irons_jewelry:material
registry.23.file=dynamic-registries/irons_jewelry_material.bin
registry.23.entries=38
registry.23.encoded-data-entries=38
registry.23.bytes=19158
registry.23.sha256=bae3140859fb582116b8ab2057300a3329ef38ae16b94775578711a76dc434ad
registry.24.name=irons_jewelry:part
registry.24.file=dynamic-registries/irons_jewelry_part.bin
registry.24.entries=27
registry.24.encoded-data-entries=27
registry.24.bytes=6300
registry.24.sha256=7938fa52f3cf0423a8cb04c91d4917b8ef264e2775bdd98f44e87f3c14e4d252
registry.25.name=irons_jewelry:pattern
registry.25.file=dynamic-registries/irons_jewelry_pattern.bin
registry.25.entries=16
registry.25.encoded-data-entries=16
registry.25.bytes=7179
registry.25.sha256=01dbdc7b71b70cedad262bf7ccf03e7f49ad7707adeb39d3f16f9841a3da1143
registry.26.name=irons_spellbooks:upgrade_orb_type
registry.26.file=dynamic-registries/irons_spellbooks_upgrade_orb_type.bin
registry.26.entries=14
registry.26.encoded-data-entries=14
registry.26.bytes=2592
registry.26.sha256=7b49f4b642d457e983a08ef16e2ac09b4c418a28cdb3723dbd2baa3ec331e0c1
registry.27.name=mekanism:robit_skin
registry.27.file=dynamic-registries/mekanism_robit_skin.bin
registry.27.entries=13
registry.27.encoded-data-entries=13
registry.27.bytes=1573
registry.27.sha256=922299807330fc838e6b9e689aeacc64f2fa01f32c2aad1d6e88f9abc25517ea
registry.28.name=minecraft:banner_pattern
registry.28.file=dynamic-registries/minecraft_banner_pattern.bin
registry.28.entries=94
registry.28.encoded-data-entries=94
registry.28.bytes=12367
registry.28.sha256=abdbf5d9092f137f87f66e45ad2392da8b2153a51f09289346cc98b50f3af906
registry.29.name=minecraft:damage_type
registry.29.file=dynamic-registries/minecraft_damage_type.bin
registry.29.entries=309
registry.29.encoded-data-entries=309
registry.29.bytes=37547
registry.29.sha256=5d012ba4ef553f1b1992bc609466cb51d972b0c4ac05d052e8d0650cd02eebe0
registry.30.name=minecraft:dimension_type
registry.30.file=dynamic-registries/minecraft_dimension_type.bin
registry.30.entries=16
registry.30.encoded-data-entries=16
registry.30.bytes=7027
registry.30.sha256=e09e9893ef2e9b8e8cc31e9372cfec90340646c047739bc276b87e5ee0df2a52
registry.31.name=minecraft:enchantment
registry.31.file=dynamic-registries/minecraft_enchantment.bin
registry.31.entries=93
registry.31.encoded-data-entries=93
registry.31.bytes=58821
registry.31.sha256=5117d9faa34235df997088f16209b42e258f33133c83caaa100eaadf340b3a96
registry.32.name=minecraft:jukebox_song
registry.32.file=dynamic-registries/minecraft_jukebox_song.bin
registry.32.entries=80
registry.32.encoded-data-entries=80
registry.32.bytes=16250
registry.32.sha256=311b408fa763697dddfb92a25506a09760d9b46cd8de44522963f10b516e028f
registry.33.name=minecraft:painting_variant
registry.33.file=dynamic-registries/minecraft_painting_variant.bin
registry.33.entries=76
registry.33.encoded-data-entries=76
registry.33.bytes=7398
registry.33.sha256=ff25f654358c160ed1f2935e400a1aaa70f66c1b8d85a3228e1b2d8a1fff044e
registry.34.name=minecraft:trim_material
registry.34.file=dynamic-registries/minecraft_trim_material.bin
registry.34.entries=43
registry.34.encoded-data-entries=43
registry.34.bytes=8877
registry.34.sha256=925a857a55db07f4137a41ea100f8ffeca7c652f1802e7049a708d37541ed749
registry.35.name=minecraft:trim_pattern
registry.35.file=dynamic-registries/minecraft_trim_pattern.bin
registry.35.entries=5
registry.35.encoded-data-entries=5
registry.35.bytes=1075
registry.35.sha256=9c879f212b0a7a49f456f2cfdb063608037a72a76d2d845d23a6ab0dc155a663
registry.36.name=minecraft:wolf_variant
registry.36.file=dynamic-registries/minecraft_wolf_variant.bin
registry.36.entries=1
registry.36.encoded-data-entries=1
registry.36.bytes=245
registry.36.sha256=72cc7cc3751a59ca8c45fac01f9c7a4915779f50dfb62d2a494c321582998a21
registry.37.name=minecraft:worldgen/biome
registry.37.file=dynamic-registries/minecraft_worldgen_biome.bin
registry.37.entries=234
registry.37.encoded-data-entries=234
registry.37.bytes=99087
registry.37.sha256=912377c52b2f317066b4e01023abc8190ac218ad093720086626f6cd363cc0a5
registry.38.name=moonlight:map_marker
registry.38.file=dynamic-registries/moonlight_map_marker.bin
registry.38.entries=35
registry.38.encoded-data-entries=35
registry.38.bytes=3364
registry.38.sha256=d696e6f3a9d12f9326c540521f8cb10d8efce0d491a7e2a0d5326d7ed5274948
registry.39.name=moonlight:soft_fluid
registry.39.file=dynamic-registries/moonlight_soft_fluid.bin
registry.39.entries=457
registry.39.encoded-data-entries=457
registry.39.bytes=205218
registry.39.sha256=148e103101e5bf9b37890fd4ade1e0d4d2ee30d2547521ee1862594b7b232213
registry.40.name=neovitae:altar_tier
registry.40.file=dynamic-registries/neovitae_altar_tier.bin
registry.40.entries=6
registry.40.encoded-data-entries=6
registry.40.bytes=32936
registry.40.sha256=d920d34f733f50661d12e87d44f5d54a192ba9e03d6b5f4b186c1c048710f500
registry.41.name=neovitae:ritual_layout
registry.41.file=dynamic-registries/neovitae_ritual_layout.bin
registry.41.entries=34
registry.41.encoded-data-entries=34
registry.41.bytes=28538
registry.41.sha256=7ba24996bf5722e311ac876340cb971080713f4c3ef1cc14b2c40d39a7d41f81
registry.42.name=neovitae:sentient_upgrades
registry.42.file=dynamic-registries/neovitae_sentient_upgrades.bin
registry.42.entries=44
registry.42.encoded-data-entries=44
registry.42.bytes=7213
registry.42.sha256=383b2065e9e2277e21fe5fd034205cb1c2bdc69fd2c675ae78e46c55a2ddf441
registry.43.name=neovitae:sigil_type
registry.43.file=dynamic-registries/neovitae_sigil_type.bin
registry.43.entries=16
registry.43.encoded-data-entries=16
registry.43.bytes=1573
registry.43.sha256=034b598fadf08c66eeb228d383177bb9527db300397e84b0b4f11e1268090e5e
registry.44.name=supplementaries:placeable_books
registry.44.file=dynamic-registries/supplementaries_placeable_books.bin
registry.44.entries=4
registry.44.encoded-data-entries=4
registry.44.bytes=564
registry.44.sha256=f16fe582258c767839f40db0e84c0363ed66e9db8be942644e9a055e3fa30dec
registry.45.name=twilight:dwarf_rabbit_variant
registry.45.file=dynamic-registries/twilight_dwarf_rabbit_variant.bin
registry.45.entries=3
registry.45.encoded-data-entries=3
registry.45.bytes=274
registry.45.sha256=5fd1845380073dca02b371b6f90852bffa1d38a36e6a6e491bf309f3c523ebfb
registry.46.name=twilight:magic_paintings
registry.46.file=dynamic-registries/twilight_magic_paintings.bin
registry.46.entries=5
registry.46.encoded-data-entries=5
registry.46.bytes=8610
registry.46.sha256=26a3d3395225064a9d1dfee47a3d8d2fa6397111f700135d75a2b4069d44f7c1
registry.47.name=twilight:restrictions
registry.47.file=dynamic-registries/twilight_restrictions.bin
registry.47.entries=9
registry.47.encoded-data-entries=9
registry.47.bytes=2330
registry.47.sha256=3a17995f1a615bb28393295b6955f1624e49feff502150beedfcf3256b5ae3a8
registry.48.name=twilight:tiny_bird_variant
registry.48.file=dynamic-registries/twilight_tiny_bird_variant.bin
registry.48.entries=4
registry.48.encoded-data-entries=4
registry.48.bytes=356
registry.48.sha256=440efbaacf82645f08e4cb2f137fc168e9ba139a201ea73639a72a7d271205d6
registry.49.name=twilight:travellers_modifiers
registry.49.file=dynamic-registries/twilight_travellers_modifiers.bin
registry.49.entries=24
registry.49.encoded-data-entries=24
registry.49.bytes=6142
registry.49.sha256=994dd0ec943d8ebf1d360dca7c05343183f91f999fdb4c4a547cc00a34d0c6c8
