format-version=2
profile-id=atm10-normal-8.1-neoforge-21.1.249
minecraft-version=1.21.1
minecraft-protocol=767
client-full-contract-sha256=9d06683c97b68f2bf5093c15d35a95ab14e8dbde67c6c9e65509cdaebed607a3
vanilla-state-table.count=26684
vanilla-state-table.sha256=de9980fae71fecd0112d77cd1c056815dca3a1e1125289efd08b1c0696f499bb
client-global-state.count=1543003
client-state-descriptor-set.count=1543003
client-state-descriptor-set.canonicalization=strip-runtime-id-sort-utf8-lf-v1
client-state-descriptor-set.sha256=02a1ec84683ac6bedb5da854bd172ea659771edf354e159db470f5c2eb42fafa
map.file=block-state-map.bin
map.bytes=63986
map.sha256=fddcfc54b25d4986b5e3189b33cb9c1585eb4c651919a3da122757c5447320c3
map.count=26684
map.maximum-target-id=27116
mapping.target-ids-strictly-increasing=true
source-global-palette.bits=15
target-global-palette.bits=21
rewrite-capabilities=BLOCK_UPDATE,CHUNK_BLOCK_STATES,BLOCK_LEVEL_EVENT,SECTION_BLOCKS_UPDATE
packet.block-update=9
packet.level-chunk-with-light=39
packet.level-event=40
packet.section-blocks-update=73
